debug: true
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    # 사용법 : h2:file:{위치}/{db명},h2:mem:///{db명}. 테이블 저장을 위해 파일형태로 함
    url: jdbc:h2:file:D:/kyu-lab/h2/boarddb
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-board
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /docs-board
    enabled: true
  swagger-ui:
    path: /swagger
    groups-order: asc
    doc-expansion: none
  cache:
    disabled: false
  model-and-view-allowed: true