server:
  port: 8002
grpc:
  server:
    port: 9002

spring:
  application:
    name: board
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# local
spring:
  config:
    activate:
      on-profile: local

---
# dev
spring:
  config:
    activate:
      on-profile: dev